name: vv_panelget
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip==23.3
  - pip:
    - pandas==2.1.2
    - requests==2.31.0
    - pytest==7.4.3
    - openpyxl==3.1.2
    - sphinx==7.2.6
    - sphinx-rtd-theme==1.3.0
    - myst-parser==2.0.0
    - sqlalchemy==2.0.23
    - google==3.0.0
    - cloud-sql-python-connector==1.4.3
    - pymysql==1.1.0
    - cryptography==41.0.7