[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "PanelSearch"
version = "1.0"
authors = [
    {name = "Tom"},
    {name = "Isabel"},
    {name = "Egle"},
    {name = "Jess"},
]
description = "A tool to manage gene panels for NHS National Genomic Testing Directory tests in the laboratory."
readme = "README.md"
requires-python = ">=3.1.2"
keywords = ["one", "two"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"',
    "pandas==2.1.2",
    "pytest==7.4.3",
    "openpyxl==3.1.2",
    "sphinx==7.2.6",
    "sphinx-rtd-theme==1.3.0",
    "myst-parser==2.0.0",
    "sqlalchemy==2.0.23",
    "pymysql==1.1.0",
    "cryptography==41.0.7",
]
dynamic = ["version"]
keywords = ["PanelApp", "VariantValidator", "Search", "Genomics", "Test", "Panel"]

[project.optional-dependencies]
pdf = ["ReportLab>=1.2", "RXP"]
rest = ["docutils>=0.3", "pack ==1.1, ==1.3"]

[project.urls]
Homepage = "https://github.com/isabelrem/2023-Software-Development-Assessment/"
Documentation = "https://manchester.readthedocs.io/en/dev/"
Repository = "https://github.com/isabelrem/2023-Software-Development-Assessment"
Issues = "https://github.com/isabelrem/2023-Software-Development-Assessment/issues"
